# ════════════════════════════════════════════════════════════════════════
# BioLab User Service — Configuration
# ════════════════════════════════════════════════════════════════════════

server:
  port: 8082

spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:biolab}?currentSchema=sec_schema
    username: ${DB_USERNAME:biolab}
    password: ${DB_PASSWORD:biolab}
    hikari:
      maximum-pool-size: 15
      minimum-idle: 5
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        default_schema: sec_schema


# ─── Security Controls ────────────────────────────────────────────────
app:
  encryption:
    # Must match auth-service key for shared PII decryption
    # key: <base64-encoded-32-byte-key>

# ─── ELK Stack ──────────────────────────────────────────────────
app:
  elk:
    logstash-host: ${LOGSTASH_HOST:logstash}
    logstash-port: ${LOGSTASH_PORT:5000}
