# ════════════════════════════════════════════════════════════════════════
# BioLab Auth Service — Configuration
# ════════════════════════════════════════════════════════════════════════

server:
  port: 8081

spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:biolab}?currentSchema=sec_schema
    username: ${DB_USERNAME:biolab}
    password: ${DB_PASSWORD:biolab}
    hikari:
      maximum-pool-size: 20
      minimum-idle: 5
      connection-timeout: 30000
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        default_schema: sec_schema
        format_sql: true

# ─── JWT Token Settings ──────────────────────────────────────────────
app:
  jwt:
    secret: ${JWT_SECRET:BioLabSecretKeyForJWTSigningMustBeAtLeast256BitsLong2026!}
    access-token-expiration-ms: 900000
    refresh-token-expiration-ms: 604800000
    issuer: biolab-auth-service

  security:
    bcrypt-strength: 12
    max-login-attempts: 5
    lockout-duration-minutes: 30
    password-history-count: 5


# ─── Security Controls (Slide 10) ─────────────────────────────────────
app:
  security:
    bcrypt-strength: 12
    max-login-attempts: 5
    lockout-duration-minutes: 30
    password-history-count: 5
    password-rotation-days: 90
    max-concurrent-sessions: 5
    anomaly-detection-enabled: true
  jwt:
    # Access token: 15 minutes (Slide 5)
    access-token-expiration-ms: 900000
    # Refresh token: 7 days (Slide 5)
    refresh-token-expiration-ms: 604800000
    issuer: biolab-auth-service
    # For RS256, set these in production:
    # rsa-public-key: classpath:keys/public.pem
    # rsa-private-key: classpath:keys/private.pem
  encryption:
    # AES-256 key (Base64-encoded) — generate for production
    # key: <base64-encoded-32-byte-key>
    key-rotation-days: 90

# ─── ELK Stack ──────────────────────────────────────────────────
app:
  elk:
    logstash-host: ${LOGSTASH_HOST:logstash}
    logstash-port: ${LOGSTASH_PORT:5000}
