package com.biolab.common.rls;

import com.biolab.common.security.CurrentUser;
import com.biolab.common.security.CurrentUserContext;
import jakarta.persistence.EntityManager;
import jakarta.persistence.PersistenceContext;
import org.aspectj.lang.ProceedingJoinPoint;
import org.aspectj.lang.annotation.Around;
import org.aspectj.lang.annotation.Aspect;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.boot.autoconfigure.condition.ConditionalOnProperty;
import org.springframework.stereotype.Component;

import java.util.Optional;

/**
 * Spring AOP aspect that enforces PostgreSQL Row-Level Security (RLS)
 * session variable hygiene on every repository method call.
 *
 * <h3>Sprint 3 — GAP-19: RLS session variable verification</h3>
 * <p>PostgreSQL RLS policies in V4 migration rely on three session-level
 * settings:</p>
 * <ul>
 *   <li>{@code app.current_user_id}   — UUID of the requesting user</li>
 *   <li>{@code app.current_user_role} — primary role (BUYER, ADMIN, etc.)</li>
 *   <li>{@code app.current_user_org_id} — primary organisation UUID</li>
 * </ul>
 *
 * <p>Without this aspect, if a service calls a repository method outside the
 * normal HTTP request lifecycle (e.g., scheduled jobs, async methods, or
 * code that bypasses {@link com.biolab.common.security.JwtAuthenticationFilter}),
 * the session variables are never set. PostgreSQL then evaluates
 * {@code current_setting('app.current_user_id', true)} as {@code NULL},
 * causing the RLS policy to silently return ZERO rows (data hiding)
 * instead of raising an error.</p>
 *
 * <h3>Behaviour</h3>
 * <ul>
 *   <li>If an authenticated user is in context: set all three variables
 *       before the query and clear them after.</li>
 *   <li>If NO user is in context (unauthenticated / scheduled job):
 *       log a warning and set variables to sentinel values
 *       ({@code __SYSTEM__}) so the RLS policy can distinguish a
 *       service-internal call from an anonymous user call.
 *       Admin-level service accounts should be given the
 *       {@code biolab_service} PostgreSQL role (V4 migration) to bypass
 *       RLS entirely for background operations.</li>
 * </ul>
 *
 * <h3>Activation</h3>
 * <p>Enabled by default. Disable for specific services that don't use RLS
 * by setting {@code app.security.rls-aspect-enabled=false}.</p>
 *
 * @author BioLab Engineering Team
 * @version 1.0.0
 */
@Aspect
@Component
@ConditionalOnProperty(name = "app.security.rls-aspect-enabled", havingValue = "true",
        matchIfMissing = true)
public class RlsContextAspect {

    private static final Logger log = LoggerFactory.getLogger(RlsContextAspect.class);

    /** Sentinel value for unauthenticated / system calls. */
    private static final String SYSTEM_PRINCIPAL = "__SYSTEM__";

    @PersistenceContext
    private EntityManager entityManager;

    /**
     * Intercepts all Spring Data repository method calls and sets PostgreSQL
     * session variables to match the current authenticated user context.
     *
     * <p>Pointcut matches any method on any interface or class in a
     * {@code repository} sub-package. This covers all {@code JpaRepository}
     * implementations generated by Spring Data.</p>
     */
    @Around("execution(* com.biolab..repository.*.*(..))")
    public Object enforceRlsContext(ProceedingJoinPoint pjp) throws Throwable {
        Optional<CurrentUser> userOpt = CurrentUserContext.get();

        if (userOpt.isPresent()) {
            CurrentUser user = userOpt.get();
            setRlsVariables(
                    user.userId().toString(),
                    primaryRole(user),
                    user.orgId() != null ? user.orgId() : ""
            );
        } else {
            // Unauthenticated — scheduled job or internal service call.
            // Set sentinel so RLS policy can distinguish from a real user with no org.
            log.debug("RLS context: no authenticated user for {}.{}() — using SYSTEM sentinel",
                    pjp.getSignature().getDeclaringTypeName(),
                    pjp.getSignature().getName());
            setRlsVariables(SYSTEM_PRINCIPAL, SYSTEM_PRINCIPAL, SYSTEM_PRINCIPAL);
        }

        try {
            return pjp.proceed();
        } finally {
            clearRlsVariables();
        }
    }

    // ─────────────────────────────────────────────────────────────────────
    // Private helpers
    // ─────────────────────────────────────────────────────────────────────

    /**
     * Sets all three RLS session variables in the current PostgreSQL connection.
     * Uses {@code set_config(name, value, is_local)} with {@code is_local=true}
     * so the variables are scoped to the current transaction only and cannot
     * leak across connection pool reuse.
     */
    private void setRlsVariables(String userId, String role, String orgId) {
        entityManager.createNativeQuery(
                "SELECT set_config('app.current_user_id',    :userId, true), " +
                "       set_config('app.current_user_role',  :role,   true), " +
                "       set_config('app.current_user_org_id',:orgId,  true)"
        )
        .setParameter("userId", userId)
        .setParameter("role",   role)
        .setParameter("orgId",  orgId)
        .getSingleResult();
    }

    /**
     * Clears RLS session variables after the query completes.
     * This is a safety measure — {@code is_local=true} in
     * {@link #setRlsVariables} already scopes them to the transaction,
     * but explicit clearing provides an additional guarantee.
     */
    private void clearRlsVariables() {
        try {
            entityManager.createNativeQuery(
                    "SELECT set_config('app.current_user_id',    '', true), " +
                    "       set_config('app.current_user_role',  '', true), " +
                    "       set_config('app.current_user_org_id','', true)"
            ).getSingleResult();
        } catch (Exception e) {
            // Non-fatal — transaction is already completing
            log.trace("RLS variable clear skipped (transaction likely rolled back): {}", e.getMessage());
        }
    }

    /**
     * Returns the primary role for a user.
     * Priority: SUPER_ADMIN > ADMIN > SUPPLIER > BUYER.
     */
    private String primaryRole(CurrentUser user) {
        if (user.hasRole("SUPER_ADMIN")) return "SUPER_ADMIN";
        if (user.hasRole("ADMIN"))       return "ADMIN";
        if (user.hasRole("SUPPLIER"))    return "SUPPLIER";
        return user.roles().isEmpty() ? "BUYER" : user.roles().get(0);
    }
}
